#proxy: 'https://some.squid.proxy:3128'
#proxy_user: 'when required by proxy'
#proxy_password: 'when required by proxy'
#
# By default we do not cache anything
#
no_cache: False
thread_pool: 10
log_level: DEBUG
#
port: 8443
server: 192.168.1.143
# docker:
#     registry: 'https://docker.tuscawilla.local:32000'
#     cacert: '/home/lane/git/creepo/demo/docker/docker.tuscawilla.local.crt'
#     credentials:
#         username: 'docker'
#         password: 'password'

# m2:
#     registry: 'https://repo.maven.apache.org/maven2'
#     # cacert: '/path/to/upstream/cacert.crt'
#     # credentials:
#         # username: 'when required by the upstream'
#         # password: 'when required by the upstream'

npm: 
  registry: 'https://registry.npmjs.org'
pip:
  registry: 'https://pypi.org/simple'

# dynamic:
#   m2: 
#     registry: 'https://repo.maven.apache.org/maven2'
#   apk: 
#     registry: 'https://dl-cdn.alpinelinux.org/alpine/'
