port: 4443
docker:
    registry: 'https://docker.tuscawilla.local:32000'
    cacert: '/home/lane/git/creepo/demo/docker/docker.tuscawilla.local.crt'
    credentials:
        username: 'docker'
        password: 'password'
