#!/bin/bash

echo "coverage"
coverage run -m pytest 
coverage html --omit="*/test*"
echo "pydoc"
python -m pydoc -w creepo
mv creepo.html pydoc.html
python -m pydoc -w creepo/*.py
sed -i 's,"creepo\.,",g' pydoc.html
mv __init__.html __main__.html
echo "pylint"
pylint .